repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.0.0
    hooks:
    - id: jupyter-notebook-cleanup
      args:
        - --pin-patterns
        - "[pin];[donotremove]"
