repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
