resources:
  repositories:
    - repository: facet
      type: github
      endpoint: konst-int-i # todo - update to final github org
      name: konst-int-i/facet # todo - update to final github org
      ref: develop
    - repository: pytools
      type: github
      endpoint: konst-int-i # todo - update to final github org
      name: konst-int-i/pytools # todo - update to final github org
      ref: develop

trigger:
- master
- releases/*

stages:
  - stage: 'Setup_and_testing'
    displayName: 'Setup & testing'

    jobs:
    - job:
      displayName: 'Setup & testing'
      pool:
          vmImage: 'ubuntu-latest'
      strategy:
        matrix:
          Python35:
            python.version: '3.5'
          Python38:
            python.version: '3.8'

      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
          displayName: 'Use Python $(python.version)'

        - checkout: self
        - checkout: facet
        - checkout: pytools
        - script: dir $(Build.SourcesDirectory)

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              eval "$(conda shell.bash hook)"
              cd $(System.DefaultWorkingDirectory)/facet/
              conda env create -f environment.yml
              conda activate facet-develop
              cd $(System.DefaultWorkingDirectory)/pytools/
              pip install -e .
              cd $(System.DefaultWorkingDirectory)/sklearndf/
              export PYTHONPATH=./src/
              pip install pytest-azurepipelines
              make package
              coverage xml
              coverage html
          displayName: "Install env and run pytest"


#        - task: Bash@3 TODO - include once packages are public
#          inputs:
#            targetType: 'inline'
#            script: |
#              eval "$(conda shell.bash hook)"
#              conda activate facet-develop
#              cd /home/vsts/work/1/s/sklearndf/
#              make package
#          displayName: "Build conda package"
