package:
  name: gamma-sklearndf
  version: {{ environ.get('FACET_BUILD_SKLEARNDF_VERSION') }}

source:
  git_url: {{FACET_PATH}}/sklearndf

build:
  noarch: python
  script: "flit install --deps none"

requirements:
  host:
    - pip>=20.*
    - python {{ environ.get('FACET_V_PYTHON', '=3.8.*') }}
    - flit>=3.0.*
# note: sklearndf.__init__ already needs pytools, pandas & sklearn:
    - pandas{{ environ.get('FACET_V_PANDAS') }}
    - scikit-learn{{ environ.get('FACET_V_SCIKIT_LEARN') }}
    - gamma-pytools{{ environ.get('FACET_V_GAMMA_PYTOOLS') }}
  run:
    - python{{ environ.get('FACET_V_PYTHON') }}
    - pandas{{ environ.get('FACET_V_PANDAS') }}
    - numpy{{ environ.get('FACET_V_NUMPY') }}
    - joblib{{ environ.get('FACET_V_JOBLIB') }}
    - scipy{{ environ.get('FACET_V_SCIPY') }}
    - pyyaml{{ environ.get('FACET_V_PYYAML') }}
    - typing_inspect{{ environ.get('FACET_V_TYPING_INSPECT') }}
    - scikit-learn{{ environ.get('FACET_V_SCIKIT_LEARN') }}
    - boruta_py{{ environ.get('FACET_V_BORUTA') }}
    - lightgbm{{ environ.get('FACET_V_LIGHTGBM') }}
    - gamma-pytools{{ environ.get('FACET_V_GAMMA_PYTOOLS') }}
test:
  imports:
    - sklearndf
    - sklearndf.classification
    - sklearndf.classification.extra
    - sklearndf.pipeline
    - sklearndf.regression
    - sklearndf.regression.extra
    - sklearndf.transformation
    - sklearndf.transformation.extra
  requires:
    - pytest=5.2.*
  commands:
    - conda list
    - python -c 'import sklearndf;
                 import os;
                 assert sklearndf.__version__ == os.environ["PKG_VERSION"]'
    - pytest -vs ${FACET_PATH}/pytools/test
    - pytest -vs ${FACET_PATH}/sklearndf/test
